const router = require('express').Router()
const userRoutes = require("./user-routes")
const roleRoutes = require("./role-routes")
const clientRoutes = require("./client-routes")
const animalRoutes = require("./animal-routes")
const clinicRoutes = require("./clinic-routes")
const inventoryRoutes = require("./inventory-routes")
const apptRoutes = require("./appt-routes")
const apiUserRoutes = require("./apiuser-routes")
const allergyRoutes = require("./allergy-routes")
const invoiceRoutes = require("./invoice-routes")

router.use("/users",userRoutes)
router.use("/roles",roleRoutes)
router.use("/clients",clientRoutes)
router.use("/animals",animalRoutes)
router.use("/clinics",clinicRoutes)
router.use("/inventory",inventoryRoutes)
router.use("/appointments",apptRoutes)
router.use("/apiuser",apiUserRoutes)
router.use("/allergies",allergyRoutes)
router.use("/invoice",invoiceRoutes)

module.exports = router